[package]
name = "tumblr_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.160", features = ["serde_derive"] }
serde_json = "1.0.95"
serde_path_to_error = "0.1.11"
