[package]
name = "tumblr_api_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = { version = "0.20.3", features = ["suggestions"] }
proc-macro2 = "1.0.66"
quote = "1.0"
syn = "2.0"
